package vu.lt.mybatis.model;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.CAR_NR
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    private String carNr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.COMPANY_ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    private Integer companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.ID
     *
     * @return the value of PUBLIC.CAR.ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.ID
     *
     * @param id the value for PUBLIC.CAR.ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.CAR_NR
     *
     * @return the value of PUBLIC.CAR.CAR_NR
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public String getCarNr() {
        return carNr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.CAR_NR
     *
     * @param carNr the value for PUBLIC.CAR.CAR_NR
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public void setCarNr(String carNr) {
        this.carNr = carNr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.COMPANY_ID
     *
     * @return the value of PUBLIC.CAR.COMPANY_ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.COMPANY_ID
     *
     * @param companyId the value for PUBLIC.CAR.COMPANY_ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
}