package vu.lt.mybatis.model;

public class CarDriver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR_DRIVER.DRIVER_ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    private Integer driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR_DRIVER.CAR_ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    private Integer carId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR_DRIVER.DRIVER_ID
     *
     * @return the value of PUBLIC.CAR_DRIVER.DRIVER_ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR_DRIVER.DRIVER_ID
     *
     * @param driverId the value for PUBLIC.CAR_DRIVER.DRIVER_ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR_DRIVER.CAR_ID
     *
     * @return the value of PUBLIC.CAR_DRIVER.CAR_ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR_DRIVER.CAR_ID
     *
     * @param carId the value for PUBLIC.CAR_DRIVER.CAR_ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }
}