package vu.lt.mybatis.model;

public class Driver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.NAME
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.COMPANY_ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    private Integer companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.ID
     *
     * @return the value of PUBLIC.DRIVER.ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.ID
     *
     * @param id the value for PUBLIC.DRIVER.ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.NAME
     *
     * @return the value of PUBLIC.DRIVER.NAME
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.NAME
     *
     * @param name the value for PUBLIC.DRIVER.NAME
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.COMPANY_ID
     *
     * @return the value of PUBLIC.DRIVER.COMPANY_ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.COMPANY_ID
     *
     * @param companyId the value for PUBLIC.DRIVER.COMPANY_ID
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
}