package vu.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.CarDriver;

import java.util.List;

@Mapper
public interface CarDriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR_DRIVER
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    int insert(CarDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR_DRIVER
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    List<CarDriver> selectAll();
}