package vu.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Car;

import java.util.List;

@Mapper
public interface CarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    int insert(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    Car selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    List<Car> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    int updateByPrimaryKey(Car record);

}