package vu.lt.mybatis.dao;

import vu.lt.mybatis.model.Company;

import java.util.List;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    Company selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    List<Company> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Sat Apr 18 22:48:04 EEST 2020
     */
    int updateByPrimaryKey(Company record);
}